### ISSUE TITLE
Failed to retrieve dependency

### ISSUE THREAD

**Issue by danbyrne84** [moriony/silex-mongo-provider#1]
Added application registration & necessary lines to composer.json and ran a 'composer update' :

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package moriony/silex-mongo-provider could not be found in a
ny version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f
  or more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common
 problems.

**Comment by moriony** [comment]
Added stable version 1.0. Now you can retrieve it with minimum stability "stable". Thanks for your comment.

**Comment by danbyrne84** [comment]
Ah, I assumed the wildcard in covered all versions (including non-stable)
Thanks for the quick response!
